pipeline:
  create_cluster:
    image: banzaicloud/pipeline-client:0.1.0
    log_level: info
    log_format: text

    cluster_name: "zeppelin-pdi-cluster"
    cluster_location: "eu-west-1"
    cluster_state: "created"

    node_image: ami-294ffd50
    node_instance_type: m4.xlarge
    node_spot_price: 0.2
    node_min_count: 1
    node_max_count: 2

    master_image: ami-294ffd50
    master_instance_type: m4.xlarge

    deployment_name: "pipeline-cluster-monitor"
    deployment_release_name: "monitor"
    deployment_state: "created"

    secrets: [ plugin_endpoint, plugin_username, plugin_password]

  install_zeppelin:
    image: banzaicloud/pipeline-client:0.1.0
    log_level: info
    log_format: text

    cluster_name: "zeppelin-pdi-cluster"
    cluster_location: "eu-west-1"
    cluster_state: "created"

    node_image: ami-294ffd50
    node_instance_type: m4.xlarge
    node_spot_price: 0.2
    node_min_count: 1
    node_max_count: 2

    master_image: ami-294ffd50
    master_instance_type: m4.xlarge

    deployment_name: "zeppelin-spark"
    deployment_release_name: "release-1"
    deployment_state: "created"

    secrets: [ plugin_endpoint, plugin_username, plugin_password]

  remote_checkout:
    image: banzaicloud/k8s-proxy:0.1.0
    original_image: plugins/git

  run:
    image: banzaicloud/k8s-proxy:0.1.0
    original_image: banzaicloud/zeppelin-client:0.1.0
    zeppelin_notebook_name: "sf-police-incidents"
    zeppelin_notebook_file_path: "sf_police_incidents.note.json"
    zeppelin_notebook_state: "running"
    zeppelin_endpoint: "http://release-1-zeppelin:8080/zeppelin"

    secrets: [ plugin_zeppelin_username, plugin_zeppelin_password ]
    
